#ifndef REPEAT_H
#define REPEAT_H

#define repeat_1(x) x
#define repeat_2(x) x, repeat_1(x)
#define repeat_3(x) x, repeat_2(x)
#define repeat_4(x) x, repeat_3(x)
#define repeat_5(x) x, repeat_4(x)
#define repeat_6(x) x, repeat_5(x)
#define repeat_7(x) x, repeat_6(x)
#define repeat_8(x) x, repeat_7(x)
#define repeat_9(x) x, repeat_8(x)
#define repeat_10(x) x, repeat_9(x)
#define repeat_11(x) x, repeat_10(x)
#define repeat_12(x) x, repeat_11(x)
#define repeat_13(x) x, repeat_12(x)
#define repeat_14(x) x, repeat_13(x)
#define repeat_15(x) x, repeat_14(x)
#define repeat_16(x) x, repeat_15(x)
#define repeat_17(x) x, repeat_16(x)
#define repeat_18(x) x, repeat_17(x)
#define repeat_19(x) x, repeat_18(x)
#define repeat_20(x) x, repeat_19(x)
#define repeat_21(x) x, repeat_20(x)
#define repeat_22(x) x, repeat_21(x)
#define repeat_23(x) x, repeat_22(x)
#define repeat_24(x) x, repeat_23(x)
#define repeat_25(x) x, repeat_24(x)
#define repeat_26(x) x, repeat_25(x)
#define repeat_27(x) x, repeat_26(x)
#define repeat_28(x) x, repeat_27(x)
#define repeat_29(x) x, repeat_28(x)
#define repeat_30(x) x, repeat_29(x)
#define repeat_31(x) x, repeat_30(x)
#define repeat_32(x) x, repeat_31(x)

#define repeat_n_1(x) concat(x, 1)
#define repeat_n_2(x) repeat_n_1(x), concat(x, 2)
#define repeat_n_3(x) repeat_n_2(x), concat(x, 3)
#define repeat_n_4(x) repeat_n_3(x), concat(x, 4)
#define repeat_n_5(x) repeat_n_4(x), concat(x, 5)
#define repeat_n_6(x) repeat_n_5(x), concat(x, 6)
#define repeat_n_7(x) repeat_n_6(x), concat(x, 7)
#define repeat_n_8(x) repeat_n_7(x), concat(x, 8)
#define repeat_n_9(x) repeat_n_8(x), concat(x, 9)
#define repeat_n_10(x) repeat_n_9(x), concat(x, 10)
#define repeat_n_11(x) repeat_n_10(x), concat(x, 11)
#define repeat_n_12(x) repeat_n_11(x), concat(x, 12)
#define repeat_n_13(x) repeat_n_12(x), concat(x, 13)
#define repeat_n_14(x) repeat_n_13(x), concat(x, 14)
#define repeat_n_15(x) repeat_n_14(x), concat(x, 15)
#define repeat_n_16(x) repeat_n_15(x), concat(x, 16)
#define repeat_n_17(x) repeat_n_16(x), concat(x, 17)
#define repeat_n_18(x) repeat_n_17(x), concat(x, 18)
#define repeat_n_19(x) repeat_n_18(x), concat(x, 19)
#define repeat_n_20(x) repeat_n_19(x), concat(x, 20)
#define repeat_n_21(x) repeat_n_20(x), concat(x, 21)
#define repeat_n_22(x) repeat_n_21(x), concat(x, 22)
#define repeat_n_23(x) repeat_n_22(x), concat(x, 23)
#define repeat_n_24(x) repeat_n_23(x), concat(x, 24)
#define repeat_n_25(x) repeat_n_24(x), concat(x, 25)
#define repeat_n_26(x) repeat_n_25(x), concat(x, 26)
#define repeat_n_27(x) repeat_n_26(x), concat(x, 27)
#define repeat_n_28(x) repeat_n_27(x), concat(x, 28)
#define repeat_n_29(x) repeat_n_28(x), concat(x, 29)
#define repeat_n_30(x) repeat_n_29(x), concat(x, 30)
#define repeat_n_31(x) repeat_n_30(x), concat(x, 31)
#define repeat_n_32(x) repeat_n_31(x), concat(x, 32)

#endif /* REPEAT_H */
